#ifndef CONSTANTS_H
#define CONSTANTS_H

// Configuration defaults
#define DEFAULT_TIMEOUT_SECONDS 10
#define DEFAULT_MAX_RETRIES 3
#define DEFAULT_WATCH_INTERVAL_SECONDS 5
#define MIN_WATCH_INTERVAL_SECONDS 1

// Category limits for tag listing
#define MIN_TAG_CATEGORY 1
#define MAX_TAG_CATEGORY 8

// Buffer sizes
#define CONFIG_BUFFER_SIZE_VAR 128
#define CONFIG_BUFFER_SIZE_VALUE 128
#define CONFIG_BUFFER_SIZE_LINE 256
#define CONFIG_FIELD_SIZE_IP 20
#define CONFIG_FIELD_SIZE_CREDENTIAL 128

// File permissions
#define CONFIG_PERMISSION_MASK 0777

// Socket connection
#define SOCKET_CONNECT_RETRIES 3
#define SOCKET_SEND_TIMEOUT_DIVISOR 2

// RSCP Protocol - Tag masks for identification
#define RSCP_TAG_BAT_NAMESPACE_MASK 0xFF000000
#define RSCP_TAG_BAT_NAMESPACE 0x03000000
#define RSCP_TAG_BAT_CONTAINER_PREFIX 0x03040000
#define RSCP_TAG_BAT_CONTAINER_MASK 0xFFFF0000
// RSCP Protocol - PVI tag masks
#define RSCP_TAG_PVI_NAMESPACE_MASK 0xFF000000
#define RSCP_TAG_PVI_NAMESPACE 0x02000000
#define RSCP_TAG_PVI_CONTAINER_PREFIX 0x02040000
#define RSCP_TAG_PVI_CONTAINER_MASK 0xFFFF0000

#define RSCP_TAG_DCB_RANGE_MASK 0xFFF00000
#define RSCP_TAG_DCB_RESPONSE_VALUE 0x03800000
#define RSCP_TAG_RESPONSE_BIT 0x00800000  // Bit 23 - converts REQUEST to RESPONSE tag

// RSCP Protocol - Data limits
#define RSCP_MAX_DATA_LENGTH 0xFFF8

// RSCP Protocol - CRC
#define RSCP_CRC_SIZE_BYTES 4
#define RSCP_CRC_NIBBLE_SHIFT 4

// Time conversions
#define MICROSECONDS_TO_NANOSECONDS 1000
#define NANOSECONDS_PER_SECOND 1000000000ULL
#define WINDOWS_FILETIME_TO_UNIX_EPOCH 116444736000000000ULL
#define WINDOWS_FILETIME_UNIT_CONVERSION 100

// AES encryption
#define AES_IV_INIT_VALUE 0xFF
#define BITS_PER_BYTE 8

#endif // CONSTANTS_H
